### PR TITLE
Test case updates

### PR DESCRIPTION
**Pull request by robela**

### CODE REVIEW

**Comment by hakimks** [comment]
Hoping that all the possible course languages are catered for here , otherwise , this would need to be updated anytime a new language is introduced. 

`public class UIUtils {
@@ -71,8 +75,23 @@ public class UIUtils {
    private UIUtils() {
        throw new IllegalStateException("Utility class");
    }
    private static final Map<String, String> iso6391ToIso6392Map = new HashMap<>();

    static {
        iso6391ToIso6392Map.put("de", "deu"); // German
        iso6391ToIso6392Map.put("fr", "fra"); // French
        iso6391ToIso6392Map.put("en", "eng"); // English
        iso6391ToIso6392Map.put("am", "amh"); // Amharic
        iso6391ToIso6392Map.put("om", "orm"); // Oromo
        iso6391ToIso6392Map.put("ti", "tir"); // Tigrinya
        iso6391ToIso6392Map.put("so", "som"); // Somali
        iso6391ToIso6392Map.put("aa", "aar"); // Afar
    }`

Otherwise all looks good.

**Comment by robela** [comment]
There are approximately 7,000 languages spoken in the world right now. I don't think it's feasible to include all of them in our app.

**Comment by hakimks** [comment]
only the local languages in Ethiopia that might be used in the courses are needed here. If that all, we can merge this PR.

**Comment by robela** [comment]
Added more local languages

**Comment by hakimks** [comment]
all good

**Review by hakimks — APPROVED** [review]
Looks good

**Comment by hakimks** [comment]
update the "def version_code = 111" in the build.gradle file by +1 to def version_code = 112
also update the "def version_name = "7.4.6.et-irt.5.int" by +1 to 7.4.7.et-irt.1.int

**Pull request merged**
